In [1]:
import numpy as np;
data = np.random.randn(1,3,4,5)
print(data)

[[[[-0.96901984 -0.46481493 -0.58382556  0.65616442 -0.14403422]
   [ 1.6380819   0.61997705  0.0453672  -0.38107674  2.62481601]
   [-1.87534049  0.97317706 -0.27118129  0.80792119 -0.07407113]
   [ 0.19603394  0.12167874  1.68892902 -1.29421388 -1.68559259]]

  [[ 0.6148012   0.52300192  1.05354665 -1.18255706 -1.00476427]
   [-0.99562833  0.26428487  0.80318967 -0.40187099  0.72988796]
   [-1.00103325 -0.84122197  1.18742231  0.32177882  1.19738946]
   [ 1.97688518  0.51063528 -1.15031023 -0.24173037  0.42714025]]

  [[-1.4062204   0.4398268  -1.9393069   0.47534956  1.55413408]
   [ 1.00573019  2.19670572  0.39932068 -1.15711961  1.06949423]
   [-0.25002496  0.60876321  0.61767275  1.25726534  0.70343973]
   [ 1.38139016 -0.95135541  0.37190691 -0.24877034  0.36615444]]]]


In [2]:
data2 = [[[1, 2, 3, 4], [5, 6, 7, 8],[2,3,5,6]]]
arr2 = np.array(data2)
print(arr2)

[[[1 2 3 4]
  [5 6 7 8]
  [2 3 5 6]]]


In [3]:
print(arr2.shape)

(1, 3, 4)


In [7]:
import tensorflow as tf;

In [8]:
import abb as a;

ModuleNotFoundError: No module named 'abb'

In [9]:
arr = np.arange(10)

print (arr)
#arr的第6个元素
print (arr[5])
#arr的第6-8个元素，[5:8]左闭右开
print (arr[5:8])

arr[5:8] = 12
print (arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [11]:
#修改切片中的操作也会转移到原数组中
arr_slice = arr
arr_slice[1]= 121312312
print (arr)

[        0 121312312         2         3         4        12        12
        12         8         9]


In [12]:
print(data+arr2)

ValueError: operands could not be broadcast together with shapes (1,3,4,5) (1,3,4) 