In [11]:
import numpy as np;
data = np.random.randn(1,3,4,5)
print(data)

[[[[ 1.00316826 -0.11539229  1.60410744 -0.13175675 -0.25643241]
   [-0.31762759  2.33797788 -1.463449    0.38273028  1.27924857]
   [-0.44690332 -0.09827596  0.35761392  0.13739498  0.06634914]
   [ 0.86934825  1.31083336 -0.12955438 -1.10273999 -0.34067521]]

  [[ 0.17894748 -0.48326395  0.56070189  0.95662339 -0.46000329]
   [ 0.15596059  0.30897195  0.76478546 -1.75154081  1.1631675 ]
   [-0.33366275 -0.21654871  0.13487263 -0.94418912 -0.71711489]
   [ 2.27958074  0.38989575  0.97061026  1.46897868 -1.53093972]]

  [[ 0.34695725 -1.24006583  0.83120239  1.41137809 -0.03046829]
   [ 0.21835754 -0.17173252 -1.03443562  0.55227946 -1.63310314]
   [-1.50485872  0.36852839  0.28654382  1.00364067 -0.87559212]
   [-0.44520512  1.69899721  1.24124461 -1.1789688  -0.17700729]]]]


In [19]:
data2 = [[[1, 2, 3, 4], [5, 6, 7, 8],[2,3,5,6]]]
arr2 = np.array(data2)
print(arr2)

[[[1 2 3 4]
  [5 6 7 8]
  [2 3 5 6]]]


In [20]:
print(arr2.shape)

(1, 3, 4)
