In [3]:
import numpy as np;
data = np.random.randn(1,3,4,5)
print(data)

[[[[ 0.1448484  -0.40350107  0.71423521  0.05344799  0.269986  ]
   [-0.91183584  0.74984469  0.27942318  0.83680281 -1.4169013 ]
   [-0.44401617  1.03052969  0.76040596 -0.19793564 -0.0375865 ]
   [-0.51327382  0.98945437 -1.28163655 -0.36022425 -0.64666532]]

  [[-0.60642845  3.11450504  0.92633265  0.22141031 -0.08198338]
   [ 2.62365172 -0.38167471 -0.25388065  0.32364838 -0.26858934]
   [ 0.28423849  0.04770949  1.02068087 -0.10759496  0.93853532]
   [ 0.98193641  1.89002848 -0.85083772 -0.6726459  -0.90289904]]

  [[ 0.16573779 -0.44221714  1.48227047 -1.30275762  0.39125191]
   [ 0.32442113  0.5448435  -1.44744854  1.77946318  0.06838365]
   [ 1.39149087  1.59832886 -0.89586177 -0.03243893  0.66225285]
   [ 1.03224231 -1.14874697  0.34023701  0.34037807 -0.65905573]]]]


In [4]:
data2 = [[[1, 2, 3, 4], [5, 6, 7, 8],[2,3,5,6]]]
arr2 = np.array(data2)
print(arr2)

[[[1 2 3 4]
  [5 6 7 8]
  [2 3 5 6]]]


In [5]:
print(arr2.shape)

(1, 3, 4)


In [6]:
import tensorflow as tf;
a=tf.constant(32)
b=tf.constant(10)


In [7]:
import abb as a;

ModuleNotFoundError: No module named 'abb'

In [ ]:
arr = np.arange(10)

print (arr)
#arr的第6个元素
print (arr[5])
#arr的第6-8个元素，[5:8]左闭右开
print (arr[5:8])

arr[5:8] = 12
print (arr)

In [ ]:
#修改切片中的操作也会转移到原数组中
arr_slice = arr
arr_slice[1]= 121312312
print (arr)

In [ ]:
print(data+arr2)

In [32]:
names = np.array(['Bob', 'Joe', 'Will',  'Will','a','b','c'])
data = np.random.randn(7, 7)

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Will' 'a' 'b' 'c']
[[-0.09301193  0.27201574  0.48483702  3.11196211 -0.42328532  0.7781265
  -0.03967692]
 [-1.20614056  1.03424063 -0.49199917 -0.42733572 -1.13079089  0.64777959
   0.47503267]
 [ 0.21269649  0.01916295  1.43477657 -0.32120781  0.9610435  -0.09512377
   1.53496977]
 [-0.84204216 -0.1176888   0.60536572  0.48413618  1.45940878  0.30597372
   2.19927549]
 [ 0.24349511 -1.22923098  1.26909414  0.33223729  1.84740298 -0.23409027
  -0.51571449]
 [ 0.48346895  0.70737299  0.05830276  1.09009581  0.35961602 -0.41260768
   0.2270602 ]
 [ 0.05346139  0.94981748 -0.06932664 -0.3756031   0.48434764  1.06380771
  -0.66514469]]


In [35]:
print(data[names== 'Bob',names== 'Bob'])

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [38]:
mask = (names == 'Bob') | (names == 'Will')
print(mask)
print(data[mask])

[ True False  True  True False False False]
[[-0.09301193  0.27201574  0.48483702  3.11196211 -0.42328532  0.7781265
  -0.03967692]
 [ 0.21269649  0.01916295  1.43477657 -0.32120781  0.9610435  -0.09512377
   1.53496977]
 [-0.84204216 -0.1176888   0.60536572  0.48413618  1.45940878  0.30597372
   2.19927549]]
